In [1]:
import numpy as np
from numpy import*
import cv2 as cv
import sys
import binascii
#filename = 'mm.jpeg'
#with open(filename, 'rb')as f:
#    content = f.read()
#print(binascii.hexlify(content))

#from matplotlib import pyplot as plt
#image = cv.imread('mm.jpeg')



from PIL import Image
im=Image.open('jeni.jpeg')
width,height=im.size
pixel_values=list(im.getdata())

r,g,b=im.split()

pixel_r=list(r.getdata())
pixel_g=list(g.getdata())
pixel_b=list(b.getdata())



if __name__=="__main__":
    
    pixel_r_data=open("./img/red.txt",'w')
    for r in range(0,50176):
        data_r="%X\n" % pixel_r[r]
        pixel_r_data.write(data_r)
        #print(data_r)
    pixel_r_data.close()
    
    
    pixel_g_data=open("./img/green.txt",'w')
    for g in range(0,50176):
        data_g="%X\n" %pixel_g[g]
        pixel_g_data.write(data_g)
        #print(data_g)
    pixel_g_data.close()
    
    pixel_b_data=open("./img/blue.txt",'w')
    for b in range(0,50176):
        data_b="%X\n" %pixel_b[b]
        pixel_b_data.write(data_b)
        #print(data_b)
    pixel_b_data.close()
    
#------------------------------------------------#    
data_rr=np.zeros((224,224),'uint8')
for i in range(224):
    for j in range(224):
        data_rr[i][j]=pixel_r[j+224*i]
pad_r=np.pad(data_rr,((1,1),(1,1)),'constant')
#print pad_r

#------------------------------------------------#
data_gg=np.zeros((224,224),'uint8')
for i1 in range(224):
    for j1 in range(224):
        data_gg[i1][j1]=pixel_g[j1+224*i1]
pad_g=np.pad(data_gg,((1,1),(1,1)),'constant')
#print pad_g

#------------------------------------------------#
data_bb=np.zeros((224,224),'uint8')
for i2 in range(224):
    for j2 in range(224):
        data_bb[i2][j2]=pixel_b[j2+224*i2]
pad_b=np.pad(data_bb,((1,1),(1,1)),'constant')
print pad_b















#--------------------------------------------------#
if __name__=="__main__":
    pad_r_data=open("./img/pad/pad_red.txt",'w')
    for y1 in range(226):
        for x1 in range(226):
            data_pad_r="%X\n" %pad_r[y1][x1]
            pad_r_data.write(data_pad_r)
        #print(data_b)
    pad_r_data.close()
#---------------------------------------------------#

    pad_g_data=open("./img/pad/pad_green.txt",'w')
    for y1 in range(226):
        for x1 in range(226):
            data_pad_g="%X\n" %pad_g[y1][x1]
            pad_g_data.write(data_pad_g)
        #print(data_b)
    pad_g_data.close()
    
#--------------------------------------------------#    
    pad_b_data=open("./img/pad/pad_blue.txt",'w')
    for y1 in range(226):
        for x1 in range(226):
            data_pad_b="%X\n" %pad_b[y1][x1]
            pad_b_data.write(data_pad_b)
        #print(data_b)
    pad_b_data.close()


[[  0   0   0 ...   0   0   0]
 [  0  40  40 ... 254 254   0]
 [  0  38  38 ... 254 254   0]
 ...
 [  0  80  57 ... 247 248   0]
 [  0  60  95 ... 246 247   0]
 [  0   0   0 ...   0   0   0]]


In [2]:
kernel =np.array([[0,0,0],[0,1,0],[0,0,0]])
kernel_width, kernel_height = kernel.shape[0], kernel.shape[1]
pad_r_width, pad_r_height = pad_r.shape[0], pad_r.shape[1]

pad_g_width, pad_g_height = pad_g.shape[0], pad_g.shape[1]

pad_b_width, pad_b_height = pad_b.shape[0], pad_b.shape[1]

stride=1

output_r_height=(pad_r_height-kernel_height)/stride+1
output_r_width=(pad_r_width-kernel_width)/stride+1
output_r=np.zeros((output_r_height,output_r_width),dtype="float32")


output_g_height=(pad_g_height-kernel_height)/stride+1
output_g_width=(pad_g_width-kernel_width)/stride+1
output_g=np.zeros((output_g_height,output_g_width),dtype="float32")

output_b_height=(pad_b_height-kernel_height)/stride+1
output_b_width=(pad_b_width-kernel_width)/stride+1
output_b=np.zeros((output_b_height,output_b_width),dtype="float32")

output_rgb=np.zeros((output_b_height,output_b_width),dtype="float32")


print pad_g_width


226


In [3]:
for y in range(output_r_height):
    for x in range(output_r_width):
        out_pixel_r=0;
        for ky in range(0,kernel_height):
            for kx in range(0,kernel_width):
                height = int(y*stride+ky)
                width = int(x*stride+kx)
                pad_r_val=pad_r[height,width]
                kernel_val=kernel[ky,kx]
                out_pixel_r+=pad_r_val*kernel_val
                output_r[y][x]=out_pixel_r
#print output_r



for y1 in range(output_g_height):
    for x1 in range(output_g_width):
        out_pixel_g=0;
        for ky1 in range(0,kernel_height):
            for kx1 in range(0,kernel_width):
                height = int(y1*stride+ky1)
                width = int(x1*stride+kx1)
                pad_g_val=pad_g[height,width]
                kernel_val=kernel[ky1,kx1]
                out_pixel_g+=pad_g_val*kernel_val
                output_g[y1][x1]=out_pixel_g
#print output_g



for y2 in range(output_b_height):
    for x2 in range(output_b_width):
        out_pixel_b=0;
        for ky2 in range(0,kernel_height):
            for kx2 in range(0,kernel_width):
                height = int(y2*stride+ky2)
                width = int(x2*stride+kx2)
                pad_b_val=pad_b[height,width]
                kernel_val=kernel[ky2,kx2]
                out_pixel_b+=pad_b_val*kernel_val
                output_b[y2][x2]=out_pixel_b
#print output_b

for rgb1 in range(output_b_height):
    for rgb2 in range(output_b_width):
        output_rgb[rgb1][rgb2]=output_r[rgb1][rgb2]+output_b[rgb1][rgb2]+output_g[rgb1][rgb2]
        
print output_rgb



[[120. 120. 120. ... 762. 762. 762.]
 [114. 114. 114. ... 762. 762. 762.]
 [108. 108. 108. ... 762. 762. 762.]
 ...
 [198. 267. 481. ... 751. 755. 755.]
 [220. 151. 245. ... 752. 752. 755.]
 [163. 268. 284. ... 749. 749. 752.]]


In [4]:
if __name__=="__main__":
    data_red=open("./img/red_result.txt",'w')
    for y1 in range(224):
        for x1 in range(224):
            data_pad_r="%X\n" %output_r[y1][x1]
            data_red.write(data_pad_r)
        #print(data_b)
    data_red.close()
#---------------------------------------------------#

    data_green=open("./img/green_result.txt",'w')
    for y1 in range(224):
        for x1 in range(224):
            data_pad_g="%X\n" %output_g[y1][x1]
            data_green.write(data_pad_g)
        #print(data_b)
    data_green.close()
    
#--------------------------------------------------#    
    data_blue=open("./img/blue_result.txt",'w')
    for y1 in range(224):
        for x1 in range(224):
            data_pad_b="%X\n" %output_b[y1][x1]
            data_blue.write(data_pad_b)
        #print(data_b)
    data_blue.close()
    
#-------------------------------------------------#    
    data_rgb=open("./img/rgb_result.txt",'w')
    for y1 in range(224):
        for x1 in range(224):
            data_rgb_re="%X\n" %output_rgb[y1][x1]
            data_rgb.write(data_rgb_re)
        #print(data_b)
    data_rgb.close()